{
 "title": "demo",
 "time": { "from": "2025-03-08T12:49:03.574Z", "to": "2025-03-08T17:02:34.072Z" },
 "panels": [
  {
   "title": "EfficientNet Predictions",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "efficientnet_predictions_total", "legendFormat": "__auto" },
    { "expr": "resnet_predictions_total", "legendFormat": "__auto" },
    { "expr": "densenet_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Objects Collected Per Generation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Collections Per Generation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Request Processing Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(request_processing_time_seconds_sum[5m]) / rate(request_processing_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Time Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "request_processing_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Virtual Memory Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}