# Use official Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

#run for download torch dependency
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# Copy only necessary files to avoid unnecessary rebuilds
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Expose the port Flask runs on
EXPOSE 5000

# Set environment variables (prevents Flask from running in debug mode)
ENV FLASK_APP=main.py

# Start the Flask server
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:app"]
