apiVersion: apps/v1
kind: Deployment
metadata:
  name: lung-cancer-api
  labels:
    app: lung-cancer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lung-cancer-api
  template:
    metadata:
      labels:
        app: lung-cancer-api
    spec:
      containers:
      - name: lung-cancer-api
        image: yuva19102003/lung-cancer-prediction:hybrid-model-backend-microservice-v2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: lung-cancer-api-service
spec:
  selector:
    app: lung-cancer-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP # Change to NodePort or LoadBalancer if needed
