apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-model-api
  labels:
    app: llm-model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-model-api
  template:
    metadata:
      labels:
        app: llm-model-api
    spec:
      containers:
      - name: llm-model-api
        image: yuva19102003/lung-cancer-prediction:llm-model-backend-microservice-v1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: llm-model-api-service
spec:
  selector:
    app: llm-model-api
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30501
  type: NodePort # Change to NodePort or LoadBalancer if needed
