apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: yuva19102003/lung-cancer-prediction:frontend-microservice-v3
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-service
spec:
  selector:
    app: frontend-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30001 # Fixed NodePort
  type: NodePort
