# Start with the official Prometheus image
FROM prom/prometheus:latest

# Set the working directory
WORKDIR /etc/prometheus

# Copy your Prometheus configuration file into the container
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose the Prometheus port
EXPOSE 9090

# Set the command to start Prometheus
CMD ["--config.file=/etc/prometheus/prometheus.yml", \
     "--storage.tsdb.path=/prometheus"]