global:
  scrape_interval: 3s # Scrape metrics every 5 seconds

scrape_configs:
- job_name: 'lung-cancer-api'
  metrics_path: '/metrics'
  static_configs:
  - targets: [ 'lung-cancer-api-service:5000' ]

- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter-service:9100' ]
